- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: Output

    - name: Printing the output
      ansible.builtin.debug:
        msg: "{{Output}}"

    - name: Taking particular thing from previous output
      ansible.builtin.set_fact:
        status: "{{Output.rc}}"

    - name: Print
      ansible.builtin.debug:
        msg: "{{status}}"
