- name: Storing output
  hosts: localhost
  tasks:
    - name: Reference of output
      ansible.builtin.shell: uptime
      Register: Output

    - name: Printing the output
      ansible.builtin.debug:
        msg: "{{output}}"