- name: Register a variable
  hosts: localhost
  tasks:
    - name: Get uptime output
      ansible.builtin.shell: uptime
      register: Output

    - name: Printing the output
      ansible.builtin.debug:
        msg: "{{output}}"